services:
  # uncomment this section and comment out the mysql section to use postgres instead of mysql
  #postgres:
    #restart: unless-stopped
    #image: postgres:14
    #container_name: postgres
    #hostname: postgres
    #volumes: 
    #  - semaphore-postgres:/var/lib/postgresql/data
    #environment:
    #  POSTGRES_USER: semaphore
    #  POSTGRES_PASSWORD: semaphore
    #  POSTGRES_DB: semaphore
  # if you wish to use postgres, comment the mysql service section below 
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    container_name: mysql_semaphore
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
  semaphore:
    restart: unless-stopped
    container_name: semaphore
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    env_file:
      - ./semaphore.env
    depends_on:
      - mysql # for postgres, change to: postgres
volumes:
  semaphore-mysql: # to use postgres, switch to: semaphore-postgres
