volumes:
  dashy_data:

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: always
    ports: 
      - 80:80
    volumes: 
      - dashy_data:/app/public/
