# image de linuxserver.io qui permet d'heberger un aridrop pour android sur un réseau local

---
services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    env_file:
      - ./pairdrop.env
    ports:
      - 3000:3000
    restart: unless-stopped
