services:
  glpi:
    image: "glpi/glpi:11.0.5"
    container_name: glpi
    restart: "unless-stopped"
    volumes:
      - "glpi:/var/glpi:rw"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "85:80"

  db:
    image: "mysql:8.4"
    container_name: mysql_glpi
    restart: "unless-stopped"
    volumes:
       - "mysql:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    expose:
      - "3306"
    ports:
      - 3307:3306

volumes:
  glpi:
    name: glpi
  glpi_www:
    name: glpi_www
  mysql:
    name: mysql