version: "2"

services:

  bookstack:

    image: linuxserver/bookstack:24.02.2
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://3T.local:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=Test123
      - DB_DATABASE=bookstackapp
    volumes:
      - bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:

    image: mariadb:lts
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Test123
      - TZ=Europe/Paris
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=Test123
    volumes:
      - bookstack_db_data:/config
    restart: unless-stopped


volumes:
  bookstack_db_data:
  bookstack_app_data:
