services:
  bookstack:
    image: linuxserver/bookstack:24.02.2
    container_name: bookstack
    env_file:
      - ./bookstack.env
    volumes:
      - bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: mariadb:lts
    container_name: bookstack_db
    env_file:
      - ./bookstack_db.env
    volumes:
      - bookstack_db_data:/config
    restart: unless-stopped


volumes:
  bookstack_db_data:
  bookstack_app_data:
