services:
  awx:
    image: ansible/awx:17.1.0
    restart: unless-stopped
    container_name: awx
    ports:
      - "8080:8052"
    env_file:
      - ./awx.env
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    restart: unless-stopped
    container_name: awx_postgres
    env_file:
      - ./postgres.env
    volumes:
      - awx_postgres_data:/var/lib/postgresql/data

volumes:
  awx_postgres_data:
