services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./wordpress.env
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    container_name: wordpress-db
    restart: unless-stopped
    env_file:
      - ./db.env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
